name: Test

on:
  pull_request:

  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Go mod vendor
        run: |
          go mod download 
      - name: Make test
        run: |
          make test
